[project]
name = "kappa-backend"
version = "0.1.0"
requires-python = ">=3.11"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:X does not have valid feature names:UserWarning",
]
pythonpath = [
    "src",
]
